### ISSUE TITLE
(BUG?) v1.1.0 doesn't load

### ISSUE THREAD

**Issue by TheComicRelief** [Terraformer9x/Terras-Rebalance#1]
It looks like this with the mod has missing logo.
![image](https://github.com/user-attachments/assets/2d3f9ef7-5043-4f85-978b-9057a08dba39)
Reverting it back to previous version works.
Here's my modpack code:01919d95-e089-68e8-0f66-71257c56911d

**Comment by Terraformer9x** [comment]
I took a look at the modpack. On my end, v1.1.0 displays an icon for me and it loads on my end. I looked through the modpack to see if anything would be causing conflicts but I didn't see anything that would be problematic.

**Comment by TheComicRelief** [comment]
It might have been caused by r2modman white screening while i was downloading the mod then.

**Comment by TheComicRelief** [comment]
But after the crash, trying to remove and redownloading no matter how many times still causes this.

**Comment by Terraformer9x** [comment]
I'm not entirely sure then, I personally use Gale and I don't run into any issues loading it.

**Comment by TheComicRelief** [comment]
Closing this as I have fixed it! It was faulty cache. All I had to do was delete it.
